apiVersion: v1
kind: Service
metadata:
  name: app5-nginx-loadbalancer-service
  namespace: test5
  labels:
    app: app5-nginx
spec:
  type: LoadBalancer
  selector:
    app: app5-nginx
  ports:
    - port: 80
      targetPort: 80
