apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginxapp2-ingress-service
  namespace: test5
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
    #appgw.ingress.kubernetes.io/override-frontend-port: "444"
    appgw.ingress.kubernetes.io/backend-path-prefix: "/"
spec:
  tls:
  - hosts:
    - uat-usnodeadmin.com
    secretName: viq-tls-secret02
  rules:
  - host: uat-usnodeadmin.com
    http:
      paths:
      - path: /test5/
        pathType: Prefix
        backend:
          service:
            name: app5-nginx-loadbalancer-service
            port:
              number: 80
        pathType: Exact
      
