apiVersion: v1
kind: Service
metadata:
  name: app2-nginx-loadbalancer-service
  namespace: test2
  labels:
    app: app2-nginx
spec:
  type: LoadBalancer
  selector:
    app: app2-nginx
  ports:
    - port: 80
      targetPort: 80
