apiVersion: v1
kind: Service
metadata:
  name: app3-nginx-loadbalancer-service
  namespace: test3
  labels:
    app: app3-nginx
spec:
  type: LoadBalancer
  selector:
    app: app3-nginx
  ports:
    - port: 80
      targetPort: 80
