apiVersion: v1
kind: Service
metadata:
  name: app4-nginx-loadbalancer-service
  namespace: test4
  labels:
    app: app4-nginx
spec:
  type: LoadBalancer
  selector:
    app: app4-nginx
  ports:
    - port: 80
      targetPort: 80
