apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginxapp1-ingress-service
  namespace: test1
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
    #appgw.ingress.kubernetes.io/override-frontend-port: "444"
    appgw.ingress.kubernetes.io/backend-path-prefix: "/"
spec:
  tls:
  - hosts:
   #- viq-test.tk
    - viq-test.tk
    secretName: viq-tls-secret
  rules:
  #- host: viq-test.tk
  - host: viq-test.tk
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app1-nginx-loadbalancer-service
            port:
              number: 80
        pathType: Exact
